<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.6.5.1 setup script
 * Date: Fri, 09 Dec 2016 23:30:35 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose']      = '';
$cfg['Servers'][$i]['host']         = 'localhost';
$cfg['Servers'][$i]['port']         = 3306;
$cfg['Servers'][$i]['socket']       = '/var/run/mysqld/mysqld.sock';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['auth_type']    = 'cookie';
$cfg['Servers'][$i]['user']         = '';
$cfg['Servers'][$i]['password']     = '';

/* End of servers configuration */

$cfg['DefaultLang']     = 'en';
$cfg['ServerDefault']   = 1;
$cfg['blowfish_secret'] = 'BLOWFISH_SECRET';
$cfg['UploadDir']       = '/tmp';
$cfg['SaveDir']         = '/tmp';
